name: Update activity readme

on:
  schedule:
    - cron: '0 4 */1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        
      - name: 🥇 Generate recent activity
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
