name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          CODE_LANG: python
          LANG_COUNT: 10
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: Binary YAML JSON TOML
          COMMIT_MESSAGE: 'chore: updated waka-readme graph with new metrics'
          TARGET_BRANCH: main
          COMMITTER_NAME: 'Wilfried AGO'
          COMMITTER_EMAIL: 'wilfriedago@pm.me'
          AUTHOR_NAME: 'Wilfried AGO'
          AUTHOR_EMAIL: 'wilfriedago@pm.me'
